### ISSUE TITLE
Adding novainstruments module to requirements

### ISSUE THREAD

**Issue by dzedu-coder** [fraunhoferportugal/tssearch#3]
Just a quick reminder to please add the novainstruments module to the requirements file, as it is not automatically imported upon setup. Thank you for all of your hard work!

**Comment by dmfolgado** [comment]
Hi! Thanks for your feedback. Thanks for pointing it out. Will do it for sure. We're still finalizing the last actions before deploying the package with PyPi. Will take that into account.

**Comment by dmfolgado** [comment]
novainstrumentation is no longer a dependency. Fixed on v0.1.3.
