### ISSUE TITLE
unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by alterreal** [fraunhoferportugal/tssearch#8]
Hi there,

I tried to run of the examples but i ran into an issue while loading the ecg sample data with tssearch.load_ecg_example()
I get the following error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> [<ipython-input-6-2e15d392c794>](https://localhost:8080/#) in <module>()
>       1 # Load the query, (optional) weight vector and sequence
> ----> 2 data = tssearch.load_ecg_example()
>       3 
>       4 # Selects the Dynamic Time Warping (DTW) as the distance for the segmentation
>       5 cfg = tssearch.get_distance_dict(["Dynamic Time Warping"])
> 
> [/usr/local/lib/python3.7/dist-packages/tssearch/examples/ecg_example_data.py](https://localhost:8080/#) in load_ecg_example()
>       8     filename = tssearch.__path__[0] + "/examples/ecg.pickle"
>       9     with open(filename, "rb") as handle:
> ---> 10         data = pickle.load(handle)
>      11 
>      12     return data
> 
> ValueError: unsupported pickle protocol: 5

_

It seems to me that there is some conflict with the pickle version. I solved it by copy the load_ecg_example() definition into my python script and installing pickle5 with pip. Could you please fix this issue for future users?

Cheers,
Alex

**Comment by dmfolgado** [comment]
Hi Alex,

It is related to the serialization protocol of the pickle file [1]. I downgraded the serialization protocol to 4 to ensure compatibility with older Python versions.

[1] https://stackoverflow.com/questions/63329657/python-3-7-error-unsupported-pickle-protocol-5
